cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest

stages:
  - build
  - test
  - deploy

build-app:
  image: node:alpine
  stage: build
  script: 
    - cd app
    - npm ci
    - npm install -g expo-cli

build-server:
  image: python:3.7.1
  stage: build
  script: 
    - cd server
    - pip install -r requirements.txt

jest-tests:
  stage: test
  script:
    - cd app
    - npm run ci-test
    - npm run lint
  artifacts:
    reports:
      junit: app/junit.xml

django-tests:
  stage: test
  script:
    - cd server
    - python -c 'print("Hello World")'


expo-prod-deployments:
  only:
    - master
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u ldsog02 -p jungle-setup
    - npx expo build:android --release-channel production

expo-staging-deployments:
  only:
    - development
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u ldsog02 -p jungle-setup
    - npx expo build:android --release-channel staging
