image: ubuntu:bionic

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/server/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - app/node_modules/
  - server/.cache/pip
stages:
  - test
  - deploy

.install-app-packages: &install_app_packages
  image: node:alpine
  before_script:
    - npm install -g expo-cli 
    - cd app
    - npm ci

.install-server-packages: &install_server_packages
  image: python:3.7.1
  before_script: 
    - cd server
    - pip install -r requirements.txt

jest-tests:
  stage: test
  <<: *install_app_packages
  script:
    - npm run ci-test
    - npm run lint
  artifacts:
    reports:
      junit: app/junit.xml

django-tests:
  stage: test
  <<: *install_server_packages
  script:
    - pip list
    - python -c 'print("Hello World")'
  
expo-prod-deployments:
  only:
    - master
  stage: deploy
  <<: *install_app_packages
  script:
    - apk add --no-cache bash
    - npx expo login -u ldsog02 -p jungle-setup
    - npx expo build:android --release-channel production

expo-staging-deployments:
  only:
    - development
    - 65-setup-ci-cd
  stage: deploy
  <<: *install_app_packages
  script:
    - apk add --no-cache bash
    - npx expo login -u ldsog02 -p jungle-setup
    - npx expo build:android --release-channel staging