cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest

stages:
  - test
  - deploy

install-app-packages:
  image: node:alpine
  script: 
    - cd app
    - npm ci
    - npm install -g expo-cli

install-server-packages:
  image: python:3.7.1
  script: 
    - cd server
    - pip install -r requirements.txt

jest-tests:
  stage: test
  before_script:
    - install-app-packages
  script:
    - cd app
    - npm run ci-test
    - npm run lint
  artifacts:
    reports:
      junit: junit.xml

django-tests:
  stage: test
  before_script:
    - install-server-packages
  script:
    - cd server
    - python -c 'print("Hello World")'
  
expo-prod-deployments:
  only:
    - master
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u ldsog02 -p jungle-setup
    - npx expo build:android --release-channel production

expo-staging-deployments:
  only:
    - development
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u ldsog02 -p jungle-setup
    - npx expo build:android --release-channel staging